easy_admin:
    site_name: 'Daily Mail'
    design:
        color_scheme: 'dark'
        brand_color: '#ff8054'
        menu:
            - { label: 'developper', icon: users,  entity: Developper }
            - { label: 'project' , icon: graduation-cap, entity: Project }
    entities:
        # List the entity class name you want to manage
        Developper:
            class: App\Entity\Developper
        Project:
            class: App\Entity\Project
            form:
                fields:
                    - { property: 'name', type: 'text'}
                    - { property: 'customer', type: 'text'}
                    - { property: 'googleSheetConfiguration', type: 'collection', type_options: { entry_type: 'App\Form\GoogleSheetConfigurationType', by_reference: true }}
                    - { property: 'trelloConfiguration', type: 'collection', type_options: { entry_type: 'App\Form\TrelloConfigurationType', by_reference: true }}
                    - { property: 'developpers'}